# main menu navigation
menu:
  Home: /
  About: /about
  Archive: /archives

widgets:
  - tag
  - archive
  - recent_posts
  - category
  - profile

# social config
social:
  zhihu:
  twitter:
  facebook:
  linkedin:
  instagram:
  github: ByteCatalyst

user:
  name: hugo
  avatar: images/avatar.png
  location: Taipei
  description: 卓越，是一種習慣
  footnotes: # footnotes

# documents: https://github.com/utterance/utterances
# API config: https://utteranc.es/
comment_utteranc:
  enable: true
  repo: ByteCatalyst/ByteCatalyst.github.io # your blog repo


# documents: https://valine.js.org/quickstart.html
comment_valine:
  enable: false
  appId:
  appKey:

comment_disqus:
    enable: false
    url:  # the url of your website main domain like this https://xxx.xxx/
    name: # the short name in disqus

# dark
# light
# user-can-set
appearance: auto # Default value is auto

# Miscellaneous
favicon: images/favicon.ico

friend_links:
  - title: Google
    link: https://www.google.com/
  - title: Github
    link: https://www.github.com/
  - title: Twitter
    link: https://twitter.com/

# Google Analytics
ga_track_id:
ga_domain:

# Baidu Analytics
ba_track_id:

# picture of about page
about_pic: about.png

image_zoom:
  enable: true